#线上环境
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?useUnicode=yes&characterEncoding=UTF8
    password: yhyc2018
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
  http:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  freemarker:
    settings:
      number_format: 0.##
  redis:
      host: localhost
      port: 6379
      #password: 123456
      timeout: 10000
      pool:
        max-active: 10
        min-idle: 3
        max-idle: 5
      database: 1
upload:
  path: D:\xiaoxin\upload
  waterMarkPath: D:\xiaoxin\water.png
server:
  port: 8888
  #address: news.cdrysj.com
ffmpeg:
  exePath: D:\Program Files\ffmpeg\bin\ffmpeg.exe
  waterPath: D:\Program Files\waterPath\water.png
nginx:
  static_url: localhost:8081




