#开发环境
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?useUnicode=yes&characterEncoding=UTF8
    password: yhyc2018
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
  http:
    multipart:
      max-file-size: 25Mb
      max-request-size: 25Mb
  freemarker:
    settings:
      number_format: 0.##
  redis:
      host: localhost
      port: 6379
      #password: 123456

      timeout: 10000
      pool:
        max-active: 10
        min-idle: 3
        max-idle: 5
      database: 1
upload:
  path: D:\xiaoxin\upload
  waterMarkPath: D:\xiaoxin\water.png

server:
  port: 8080
ffmpeg:
  exePath: D:\Program Files\ffmpeg\bin\ffmpeg.exe
  waterPath: D:\Program Files\waterPath\water.png
nginx:
  static_url: localhost:8081




