#开发环境
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?useUnicode=yes&characterEncoding=UTF8
    password: yhyc2018
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
  http:
    multipart:
      max-file-size: 10MB
  freemarker:
    settings:
      number_format: 0.##

upload:
  path: D:\xiaoxin\upload
server:
  port: 8888
ffmpeg:
  exePath: D:\Program Files\ffmpeg\bin\ffmpeg.exe
  waterPath: D:\Program Files\waterPath\water.png
nginx:
  static_url: localhost:8081




